import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Plugin to rename main.css to styles.css (Obsidian convention)
const renameCSS = {
  name: 'rename-css',
  setup(build) {
    build.onEnd(() => {
      if (fs.existsSync('main.css')) {
        fs.renameSync('main.css', 'styles.css');
      }
    });
  },
};

const options = {
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules],
  format: 'cjs',
  target: 'ES2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  plugins: [renameCSS],
};

if (prod) {
  await esbuild.build(options);
  process.exit(0);
} else {
  const context = await esbuild.context(options);
  await context.watch();
}
